### ISSUE TITLE
Nothing is new_

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#1753]
Targets for renaming:

- [x] `templates/package/new_package_form.html` #1659
- [x] `new_authz.py` #1995 
- [x] old `tests` become `tests/legacy` #2221
- [x] `new_tests` become `tests` #2349

**Comment by wardi** [comment]
Thank you @vitorbaptista @amercader @davidread @joetsoi !!!

**Comment by davidread** [comment]
:+1:
