### ISSUE TITLE
Python 3 support (OLD)

### ISSUE THREAD

**Issue by sirex** [ckan/ckan#3309]
Add Python 3 support.

[Python 2.7 support will end in 2 years](https://pythonclock.org/).

- [x] add Python 3 support to [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree): ~https://github.com/okfn/ofs/pull/14~, ~https://github.com/benosteen/pairtree/pull/2~
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree), they were needed by the old Filestore.
- [ ] replace Pylons with Flask: ckan/ckan#3119
- [x] remove [ordereddict](https://pypi.python.org/pypi/ordereddict)
- [ ] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree) dependencies as they are no longer used
- [ ] migrate away from vdm or add Python 3 support to vdm since getting rid of vdm seems like a not an easy task, okfn/vdm#13
- [ ] replace [webhelpers](https://pypi.python.org/pypi/WebHelpers) with a modern alternative
- [ ] replace [repoze.who-friendlyform](https://pypi.python.org/pypi/repoze.who-friendlyform) with a modern alternative
- [ ] add Python 3 support to the ckan own code base
- [ ] Replace Paste with Click #4639

**Comment by sirex** [comment]
I did some review of ckan dependencies and found following dependencies that do not support Python 3:

- [ofs](https://pypi.python.org/pypi/ofs) - last update: 2013-12-26
- [ordereddict](https://pypi.python.org/pypi/ordereddict) - last update: 2010-10-28
- [Pairtree](https://pypi.python.org/pypi/Pairtree) - last update: 2010-10-13
- [Pylons](https://pypi.python.org/pypi/Pylons) - last update: 2015-07-22
- [repoze.who-friendlyform](https://pypi.python.org/pypi/repoze.who-friendlyform) - last update: 2010-11-14
- [vdm](https://pypi.python.org/pypi/vdm) - last update: 2014-08-12
- [WebHelpers](https://pypi.python.org/pypi/WebHelpers) - last update: 2011-03-24

It looks like most of these packages are no longer maintained.

**Comment by sirex** [comment]
After fixing https://github.com/ckan/ckan/issues/3119 Python 3 support will be much easier, since there will be no Pylons dependencies.

**Comment by deinok** [comment]
[https://requires.io/github/ckan/ckan/requirements/?branch=master](https://requires.io/github/ckan/ckan/requirements/?branch=master)

This can be useful

**Comment by amercader** [comment]
`ofs` and `pairtree` were only needed by the old filestore. I think it's safe to remove them for the next version. `ordereddict` we don't need any more as we are targeting Python >= 2.7. You can get rid of these in a PR if you want.

As you say, one of the multiple benefits of the Flask migration will be to get rid of `Pylons` .

That leaves us with `vdm`, which is next on our hit list of ugly old code to get rid of (see https://github.com/ckan/ideas-and-roadmap/issues/41). For `webhelpers` and `repoze.who-friendlyform` I'm sure we can find more modern alternatives.

Actually replacing `webhelpers` seems like a nice piece of work in case someone has some availability.

**Comment by torfsen** [comment]
Great to see work towards Python 3 support!

Don't forget the Unicode issues: In Python 2, string literals are byte strings while in Python 3 they are Unicode. Hence some of CKAN's code might be Python 3 compatible from a syntax point-of-view but still have different semantics on Python 2 and Python 3. The current approach is to [explicitly mark all Unicode string literals using the `u` prefix](http://docs.ckan.org/en/latest/contributing/unicode.html#string-literals). However, that [hasn't been done in most files](https://github.com/ckan/ckan/blob/896acf460d6d9beb4802b41fe67a194d7f5a8164/ckan/tests/test_coding_standards.py#L233).

**Comment by amercader** [comment]
So, pieces of work for someone willing to help with this:

- [ ] Remove ofs, pairtree and ordereddict requirements
- [ ] Replace WebHelpers with a more modern, py3 enabled alternative

**Comment by brylie** [comment]
I would like to help. Which of the packages above has the least usage in CKAN? I would need something bite sized, since I am learning the CKAN codebase.

**Comment by brylie** [comment]
One idea would be to replace [wevhelpers.feedgenerator](https://webhelpers.readthedocs.io/en/latest/modules/feedgenerator.html) with a Python 3 compatible library, such as [python-feedgen](https://pypi.python.org/pypi/feedgen/).

**Comment by TkTech** [comment]
@brylie alternatively there's no need for either of those, since Jinja can happily generate the feeds.

**Comment by brylie** [comment]
Fewer dependencies seems better to me! :smile:

**Comment by antonkulaga** [comment]
Any updates on this? Using outdated python2 creates a HUGE amount of problems. Many libraries (at least those that we use in the lab) are already python3 only that makes writing CKAN plugins much more coplicated

**Comment by torfsen** [comment]
@amercader: This was auto-closed by your merge of #3845, but I don't think that #3845 solves all of the issues mentioned here :wink:

**Comment by antonkulaga** [comment]
@torfsen, @sirex  maybe you should re-open?

**Comment by sirex** [comment]
I don't have permission to repoen, but I agree, this should be reopened. @amercader ?

**Comment by sirex** [comment]
Brought some Python 3 support to https://github.com/okfn/ofs/pull/14, at least package can be installed and imported without errors under python 3.

**Comment by cclauss** [comment]
Based on my very limited knowledge of the project, an updated checklist given the recent changes:
- [ ] [Meta] General feedback or comments regarding the Flask migration #3119
- [ ] Deprecate webhelpers.feedgenerator and use Jinja for feeds #3592 
- [ ] Convert ur'strings' --> u'strings' for Python 3 #4052
- [ ] Remove old Celery-based tasks #4055
- [ ] Fix reload() for Python 3 #4058
- [ ] Fix cmp() for Python 3 #4059

Requirements: See https://requires.io/github/ckan/ckan/requirements/?branch=master
- [ ] httpretty -- Could we shift to [mocket](https://github.com/gabrielfalcao/HTTPretty/issues/325#issuecomment-347029522) instead?
- [ ] fanstatic -- need to upgrade
- [ ] okfn/ofs#14 -- is this still needed?
- [ ] benosteen/pairtree#2 -- is this still needed?
- [ ] Paste -- need to upgrade
- [ ] pyutilib.component.core -- could upgrade from PyUtilib/pyutilib#30
- [ ] repoze.who-friendlyform -- is this still needed?
- [ ] okfn/vdm#13 -- is this still needed?

Other:
- [ ] a Python 3 Docker image
- [ ] updates to __.travis.yml__
- [ ] updates to __circle.yml__
- [ ] test... fix... test... fix... test... fix...

**Comment by deinok** [comment]
In my opinion the correct order is:
* Strings to Unicode Strings
* Move to Flask
* Update ALL libs to its latest version
* Remove unsuported Py3 libs
* Close Py2 support and only allow Py3
* Experimental release of a new version
* Next release is only bug fixes, no features

**Comment by cclauss** [comment]
IN that scenario, there would be no release that would be supported to run on __both__ Python 2 and Python 3?

**Comment by deinok** [comment]
@cclauss No (In my opinion) 
Also for the process of mantaining the libs i would suggest -> https://dependabot.com/python.html

**Comment by wardi** [comment]
we certainly want to support both 2 and 3 for a number of releases. Extension developers need time to catch up

**Comment by deinok** [comment]
Well, then the migration its going to be really hard.
But if we are going to do this migration we need to it really well

**Comment by sirex** [comment]
I would like to accasionally contribute to this migration to python 3. But recently I started to work on some changes, but then I found, that there are several open pull requests, where some of the changes are already done, but not merged to master. So it is hard to know, what is already been fixed and what is missing.

Maybe it would be possible to split some how all work, to avoid stepping on other toes?

Probably best option would be to create list of tasks then claim a task.

Just thinking...

**Comment by deinok** [comment]
@sirex I can work on:
* CI integration (Py2, Py3, Docker)
* Updating Libs

Also, i would like to see an "Epic" issue for traking the Python 3 migration and information about who would do what.

**Comment by cclauss** [comment]
Please open two separate issues on two bullet items above.

Also, could we get comments from the experts on the modules that [listed above](https://github.com/ckan/ckan/issues/3309#issuecomment-369720863)?  I would suspect that some of them will no longer be required once we drop Pylons.  Of special interest are __ofs__, __pairtree__, and __vdm__.

**Comment by cclauss** [comment]
No more Python 3 syntax errors in this repo... #4052 is merged.

**Comment by deinok** [comment]
@cclauss Done

**Comment by sirex** [comment]
@cclauss pairtree already supports python 3, just needs to be upgraded.

**Comment by davidread** [comment]
@sirex I hope you don't mind me updating this issue's main description - I've drawn together info from @amercader and elsewhere to try and make this the definitive place for coordinating getting CKAN python3 support over the line.

**Comment by sirex** [comment]
@davidread sure, go ahead.

**Comment by davidread** [comment]
Apologies, there was a request for a fresh ticket, so this is now superceded by: https://github.com/ckan/ckan/issues/4681
