### ISSUE TITLE
Deprecations in CKAN 2.7

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#3536]
This ticket is for tracking the upcoming 2.7 release aimed at deprecating or flagging behavior changing in the next major release. I would also recommend we make this an "LTS" kind of release we'll backport fixes to for quite awhile.

### API

- [x] `/api/rest/*` will be removed in favour of action API introduced in CKAN 2.0
- [ ] All `*_html` actions will be removed in favour of simple Jinja2 templates.
- [ ] All `*_activity_list` actions will be removed in favour of a single activity endpoint.
- [ ] All actions where it makes sense will be paginated. Currently many methods return complete sets [built in memory] which cause significant performance problems.
- [ ] Activity-related actions will switch to sorting and offset based on timestamp.

### Frontend

- [x] Announce deprecation of Bootstrap 2 on the next release (2.8) See https://github.com/ckan/ckan/pull/3547#issuecomment-302437127

### Misc.

- [ ] The legacy revisions controller (`/revisions/list`, etc...) will be completely removed.
- [ ] The package history view will be completely removed. Instead, you can view the package at any point in time based on `Activity` records.
- [ ] Revisions/VDM themselves will be deprecated in favour of improved activity.
- [ ] Celery based tasks in favour of RQ jobs
- [x] Feeds must use use v3 api endpoints (#3542)

## Fixes

- [ ] `number_of_packages` and `number_of_revisions` changed from dynamic fields to pre-calculated trigger-based fields on Users, significantly improving performance for both logged in users and user_list. (Requires migration)
- [ ] Activity APIs and views now respect `permission_labels`, fixing many issues. (Requires migration)

**Comment by wardi** [comment]
I put `/api/rest` at the top because it seemed important :-)

**Comment by torfsen** [comment]
From my point of view, the Celery-based background jobs can be deprecated in favor of the RQ-based solution. Code, documentation and deprecation notices are in `master`.

**Comment by timgiles** [comment]
Is beta.ckan.org running the latest built?

**Comment by wardi** [comment]
when this goes in I'd like to switch all use of `unicode` in validators to `unicode_only` https://github.com/ckan/ckan/pull/3428/files#diff-38644dde5577e621a00643c43bfec0feR120
