### ISSUE TITLE
CKAN 2.7 Checklist

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3623]
This is a rough checklist of what should happen to get 2.7 out. The detailed guidance is still at http://docs.ckan.org/en/latest/contributing/release-process.html.

## Main release

- [x] Branch out `dev-v2.7` and update version number
- [x] Extract translations, upload to Transifex and announce
- [x] Create `release-v2.4.8`, `release-v2.5.6` branches, update version numbers
- [x] Change version number in `dev-v2.6`
- [x] Merge all open PRs marked with [`Backport Pending`](https://github.com/ckan/ckan/pulls?q=is%3Apr+label%3A%22Backport+pending%22+is%3Aopen)
- [x] Cherry-pick all changes from merged PRs marked with [`Backport Pending`](https://github.com/ckan/ckan/pulls?q=is%3Apr+label%3A%22Backport+pending%22+is%3Aclosed)
- [x] Update https://beta.ckan.org to 2.7
- [x] Build beta package and upload to http://packaging.ckan.org/
- [x] Finalize Changelog, including deprecation notices for everything relevant in #3536
     *Added all main deprecations in #3536. Just missing to update the final date and add any last minute significant changes*
- [x] Update Changelog for each release
- [x] Announce beta, request testing
    *Done 19th July*
- [x] Build and test packages
- [x] Fix any *important* issues flagged by testers (at the discretion of the release manager)
- [x] Announce a week before on ckan-announce ([example](https://lists.okfn.org/pipermail/ckan-announce/2016-October/000023.html)). Unless there is a really severe issue I suggest freezing the release branches from now on.
    *Wed 26th July*
- [x] Merge translations
     *I've merged the existing translations today (13th July) for 2.6 and 2.7 (don't bother with 2.4 and 2.5). Do a final merge around 24th July.*
- [x] Do a final build of the front-end (`paster front-end-build`)
- [ ] Final release (see [docs](http://docs.ckan.org/en/latest/contributing/release-process.html) for details on each of the steps)
    *Wed 2nd August*
    - [x] Review the CHANGELOG to check it is complete. Add the release date to the new versions.
    - [x] Check that the docs compile correctly.
    - [x] Remove the beta letter in the version number.
    - [x] Tag the repository with the version number.
    - [x] Merge the `release-v2.4.8`, `release-v2.5.6` and `dev-v2.6` branches to `release-v2.4-latest`, `release-v2.4-latest` and `release-v2.6-latest` respectively (we won't do that anymore starting with 2.7)
    - [x] Create and deploy the final deb packages. Note that the packages created will need to be renamed, and the `md5sum` file updated. Packages should be uploaded to `s3://packaging.ckan.org`. New patch
 release packages replace the existing ones.
    - [x] Upload the release to PyPI.
    - [x] Enable the new version of the docs on Read the Docs.
    - [ ] Announce it to ckan-announce (added missing tech team members as admins) & ckan-dev ([example](https://lists.okfn.org/pipermail/ckan-announce/2016-November/000024.html)) & twitter.

## Post release tasks

These can be done after the release day, but I suggest doing them on the day or as soon as possible so they aren't forgoten.

* [x] Cherry-pick the i18n changes from the release branch onto master. Basically ignore any conflicts, the i18n folder in `master` should be the same as in `dev-v2.7`.
* [x] Update the changelog in master to reflect changes in all versions. There are some currently missing in master now (eg 2.6.2)
* [ ] Write a blog post on ckan.org/blog

**Comment by torfsen** [comment]
How is decided which issues are going to be blockers for 2.7? A new minor release would be a good time to introduce the new background job system, but we'd need to fix #3606 before. It would be nice to have a rough time plan so that I can see whether I find time for doing that.

**Comment by amercader** [comment]
@torfsen It's hard to track everything going on so raising individual issues as you did is the best way. You are right that it would be really good to include this in 2.7.

I've added the Backport Pending label to #3606. In terms of timeline releases tend to take 3-4 weeks since branching (which happened last week) but always depending on resources. A patch like this which is well defined and easy to test should be easy to get even later in the process sometime next week or the next one would be ideal.

**Comment by tino097** [comment]
@amercader release 2.5.6 is built as 2.5.5b again

**Comment by amercader** [comment]
@smotornyuk I've updated the checklist to reflect all tasks. Don't worry it looks like a lot but they are mostly really small tasks.

Can you please review all outstanding steps to make sure they make sense and that you have access to the necessary places? (Don't worry about Twitter or the blog post, I'll coordinate that separately).

**Comment by amercader** [comment]
CKAN 2.7 is out, thanks to @smotornyuk great work.
