### ISSUE TITLE
[Python3] - CI

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#4060]
ref:  #3309

The transition to Python3 and support of Python2 will require changes to the CI system.

I would recommend using CircleCI V2: https://circleci.com/docs/2.0/
And follow the following steps:

# Roadmap:
- [ ] Step 1: Port CircleCI V1 file to CircleCI V2
- [ ] Step 2: Enable CircleCI V2 Workflows https://circleci.com/docs/2.0/workflows/
- [ ] Step 3: Add Python 2 as a Workflow -> `python2`
- [ ] Step 4: Add Docker-Python2 test as a Workflow -> `docker-python2`
- [ ] Step 5: Remove TravisCI as it won't be required at this moment.
- [ ] Step 6: Add Python 3 as a Workflow -> `python3`. This test will fail until completely ported to Python 3. Set an easy mechanism to enable and disable this workflow. Disabled by default.
- [ ] Step 7: Add Docker-Python3 test as a Workflow. This test will fail until completely ported to Python 3. Set an easy mechanism to enable and disable this workflow. Disabled by default.
- [ ] Step 8: Python 3 is supported.
- [ ] Step 9: Set `python3` Workflow enabled by default.
- [ ] Step 10: Set `docker-python3` Workflow enabled by default.

# Related Issues:
Closes #4227 #4213

**Comment by deinok** [comment]
@wardi I shouldn't require anything fixed until Step 3 is finished. So I will wait for your confirmation that everything is okey with this steps, and start working on it ;)

**Comment by cclauss** [comment]
I would be interested to see [this test}(https://github.com/ckan/ckan/pull/4054/files#diff-354f30a63fb0907d4ad57269548329e3R19) added to the current __.travis.yml__ or __circle.yml__ so that we do not see backsliding on syntax errors and undefined names.  It would be especially valuabe if we could also get it [running on both Python 2 and Python 3](https://travis-ci.org/ckan/ckan/builds/347762819?utm_source=github_status&utm_medium=notification) quickly.

**Comment by deinok** [comment]
@cclauss LGTM, im not expert in Python Linting but i really care about the style.
Adding it to the CI should not be a problem, this can be added inside the `python2` and `python3` workflows.
@wardi Are you agree with adding a lint system?
Also, is flake8 the recommended tool?

**Comment by deinok** [comment]
As a reference of other linting tools for python:
* Pylint
* Pep8
* Flake8
* Pyflakes
* Pychecker
* Mypy
* PyLama

I think that we should select a lint that comes from https://github.com/PyCQA and follows PEP8

**Comment by cclauss** [comment]
Pylint, PEP8 (now called Pycodestyle at the BDFL's request), Flake8, and Pytflakes all come from PyCQA.  Flake8 is a superset of Pycodestyle, pyFlakes, and McCabe complexity analysis.  I like flake8 over pylint because it finds undefined names (like __basestring__ in Python 3) and pylint does not.  MyPy depends on type annotations which is a bit too early for in this codebase.

I would be most interested to hear if any of the others can find undefined names.

**Comment by deinok** [comment]
IDK, as I said im not an expert in linting python, so wont give a recommendation or vote for anything except that the lint system we select comes from a stable package

**Comment by cclauss** [comment]
For the workflows, can we call them __legacy_python__ and __python__ so we don't create rework in Python 4, 5, ...?  ;-)

**Comment by cclauss** [comment]
4132 contains the __flake8__ linting on Python 3 in __allow_failures__ mode.

**Comment by amercader** [comment]
This roadmap looks really sensible. I guess the next step is #4213 @deinok @cclauss is any of you up for that ? :)

**Comment by deinok** [comment]
Yeah, also CircleCI 1.0 will be shutdown at the end of the summer i think.

**Comment by deinok** [comment]
@amercader I supose I have your confirmation to start executing the steps above.
I will start working on on this, this weekend

**Comment by deinok** [comment]
@amercader Can we close all other Issues related on CircleCI and start using this as a meta-issue, so we can centralize the roadmap of CircleCI related issues?

**Comment by cclauss** [comment]
My sense is that your list above is correct but there is a __missing step 0__
Before the __Port CircleCI V1 file to CircleCI V2__ can be done by the [__Circle CI converter__]()
- [ ] Step 0: Port CircleCI V1 file from __Ubuntu 12.04 (Precise)__ --> __Ubuntu 14.04 (Trusty)__
 #4347

**Comment by cclauss** [comment]
@deinok The roadmap above seems to be all the right stuff...  Has any new progress been made on this effort?

CircleCI v1 will stop functioning at the end of this month.

**Comment by deinok** [comment]
this is blocking #4290

**Comment by davidread** [comment]
@deinok @wardi Nice job getting the CircleCI v2 done https://github.com/ckan/ckan/issues/4213. That's Step 1 here. @deinok are you still up for setting up the workflows?

**Comment by cclauss** [comment]
Can we close this issue?

**Comment by frafra** [comment]
@amercader I think this issue can be closed, as Python 3 has been added to the CI system.
