### ISSUE TITLE
2.8 + patch releases tracker

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#4228]
This is just an issue to track progress on the 2.8 and patch releases scheduled for Wed 9th May

[Full docs](http://docs.ckan.org/en/latest/contributing/release-process.html)

* [x] [Cherry-picks 2.8](https://github.com/ckan/ckan/labels/Pending%202.8.0)
     - [x] #4215 + #4225 (? if finished soon)
     - [x] Rest 
* [x] Docs reorganization #4209 
* [x] Pull translations
* [x] Rebuild Frontend
* [x] Changelog
    - [x] 2.8
    - [x] Patch releases
* [x] Change version and tag 
* [x] Build packages
* [x] PyPI
* [x] Announce

**Comment by amercader** [comment]
2.8 is out, thanks @tino097 for your work on this.

**Comment by wardi** [comment]
great work guys!
