### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#4681]
**Update:** 

* Check the full roadmap here: https://hackmd.io/TI0UaFncR6yM9QIZDYxvsg
* GitHub Project: https://github.com/ckan/ckan/projects/3
* Python 3 issues: https://github.com/ckan/ckan/labels/Python%203

---

Add Python 3 support. [Python 2.7 support ends Dec 2019](https://pythonclock.org/).

## Core CKAN

- [x] 1.1 Support Py3 in the codebase - exceptions #3309, long #4015, xrange #4017 #4045, basestring #4029, strings #4035 #4039 #4051 #4052 #4057, reload #4058, cmp #4059
- [x] CI runs tests in python 3 #4060
- [x] 2.1 Remove VDM
    - [x] Revision UI removed & activity stream improved - https://github.com/ckan/ckan/pull/3972 @davidread 
    - [x] vdm removal - @TkTech (@davidread did exploratory work in #4664)
- [x] 2.2 Pylons
    - [x] blueprints migrations and addressed several Flask related issues. What is left is:
    - [x] 2.2.1 Migrate datastore and other core extensions controllers (issue TBD)
    - [x] 2.2.2 Small bits of Pylons code in tests etc
    - [x] 2.2.3 Refactor CLI to make drop paste.script: @tino097 has done the first initial work and now it's just a matter of migrating commands to a new syntax. Details: https://github.com/ckan/ckan/issues/4639#issuecomment-460776340 and overall progress surfaced here:
        - [x] check-po-files [#4701]
        - [x] color [dropped]
        - [x] config-tool  [#4702]
        - [x] create-test-data [#4703] 
        - [x] datapusher [#4707]
        - [x] dataset [#4708]
        - [x] datastore [#4712]
        - [x] db
        - [x] front-end-build
        - [x] jobs
        - [x] less
        - [x] minify
        - [x] notify
        - [x] plugin-info
        - [x] profile
        - [x] ratings [dropped]
        - [x] rdf-export
        - [x] search-index
        - [x] sysadmin
        - [x] tracking
        - [x] trans [#4701]
        - [x] user
        - [x] views
    - [x] 2.2.4 Write migration guide for extension developers
    - [ ] 2.2.5 Migrate selected extensions to make sure they don't require Pylons. For the most commonly used ones that are following conventions this should not be a big job. There are certain compatibility issues for extensions that need to support both pre and post Flask CKAN versions but we'll deal with those as we go
    - [x] 2.2.6 Unknown minor issues that will surface as we use more and more the new version
    - [ ] 2.2.7 Decide and implement a deprecation plan that allows people to migrate and ends up with a Flask only/ Py3 CKAN version by the end of the year (integrated in the wider roadmap that Kevin put together)

- [x] remove [ofs](https://pypi.python.org/pypi/ofs) and [pairtree](https://pypi.python.org/pypi/Pairtree), they were needed by the old Filestore [#4750]
- [x] replace [webhelpers](https://pypi.python.org/pypi/WebHelpers) with a modern alternative
- [ ] replace [repoze.who-friendlyform](https://pypi.python.org/pypi/repoze.who-friendlyform) with a modern alternative

## CKAN Extensions
Tasks:
1. Support Py3 in the code - running lib2to3, using six, etc
2. Migrate off Pylons. For the most commonly used ones that are following conventions this should not be a big job. There are certain compatibility issues for extensions that need to support both pre and post Flask CKAN versions but we'll deal with those as we go

(I've suggested who might do these migrations, based on who seems to be maintaining / using the extension currently)

- [ ] [ckanext-harvest](https://github.com/ckan/ckanext-harvest) - @amercader ?
- [ ] [ckanext-spatial](https://github.com/ckan/ckanext-spatial) - @amercader ?
- [ ] [ckanext-dcat](https://github.com/ckan/ckanext-dcat) - @amercader ?
- [ ] [ckanext-scheming](https://github.com/ckan/ckanext-scheming) - @wardi ?
- [ ] [ckanext-pages](https://github.com/ckan/ckanext-pages) - @TkTech preparing PR (was @torfsen)
- [ ] [ckanext-geoview](https://github.com/ckan/ckanext-geoview) - @pduchesne / @amercader ?
- [ ] [ckanext-googleanalytics](https://github.com/ckan/ckanext-googleanalytics) - @maxious / @smotornyuk ? 
- [ ] [ckanext-qa](https://github.com/ckan/ckanext-qa) - @Zharktas
- [ ] [ckanext-showcase](https://github.com/ckan/ckanext-showcase) - @amercader ?
- [ ] [ckanext-pdfview](https://github.com/ckan/ckanext-pdfview) - @jqnatividad ?
- [ ] [ckanext-xloader](https://github.com/ckan/ckanext-xloader) - @davidread ?
- [ ] [ckanext-basiccharts](https://github.com/ckan/ckanext-basiccharts) - ?
- [ ] [ckanext-archiver](https://github.com/ckan/ckanext-archiver) - @Zharktas
- [ ] [ckanext-fluent](https://github.com/ckan/ckanext-fluent) - @wardi ?
- [ ] [ckanext-mapviews](https://github.com/ckan/ckanext-mapviews) - ?

(These are listed because they are in the CKAN GitHub organization and seem active - see the [analysis](https://docs.google.com/spreadsheets/d/1oEAp68C8aGQj08vU9pVSAoDDICYR-y9EUl4Aunz45Lc/edit#gid=346652840))

**Comment by amercader** [comment]
Thanks @davidread , I added a new item 2.2.1 which I forgot on my initial summary.

**Comment by davidread** [comment]
I've added the CI setup.

**Comment by Zharktas** [comment]
I can add migration of qa and archiver to our internal task list so it gets eventually done, need to migrate some extensions anyway. But I probably need migration guide for that first.

**Comment by torfsen** [comment]
Regarding ckanext-pages: as already mentioned on the ckan-dev mailing list I'm changing jobs and won't be able to spend much time on CKAN development anymore.

If I find time I'll happily contribute, but unfortunately I can't guarantee anything.

**Comment by TkTech** [comment]
Part of the work early last year for NDHS included modernizing ckanext-pages (including py3) and adding full multilingual support to the editor UI. This work was finished but looks like it never ended up in a PR. I'll cherry pick it out and get a PR up this weekend.

**Comment by cclauss** [comment]
250 days until Python 2 end of life.

**Comment by poligarcia** [comment]
Hi @amercader! At @devartis we are interested in helping this issue come together. Is there a way in which we can contribute with some hours to submit or review PR?

**Comment by amercader** [comment]
Hi @poligarcia , that's really great! Absolutely, everything in the [Github project](https://github.com/ckan/ckan/projects/3) is up for grabs. It is roughly ordered by priority but anything marked "Good for Contribution" would be a good thing to take on. Also you can focus on the [Beginner Friendly](https://github.com/ckan/ckan/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22Python+3%22+label%3A%22Beginner+Friendly%22) ones if you want easier stuff to get familiar with. #4639 needs some hands as well.

Let me know if you can take on any of these and we can discuss on the relevant issue if you need more help.

**Comment by pwalsh** [comment]
@amercader @davidread @wardi 

As noted in https://github.com/ckan/ckan/issues/4681#issuecomment-471939262 a migration guide would be really helpful, especially as this will be done over many codebases. It is far from as simple as just use six, and if we want some consistency a brief guide could go a long way.

I've done a number of Py2/Py3 codebases and would be happy to prepare such a guide if no one on the tech team is already doing one.

For inspiration, see:

- https://docs.djangoproject.com/en/1.11/topics/python3/

**Comment by davidread** [comment]
@pwalsh Yes, I'd love something tightly focused on the needs of CKAN extensions, based on the work we've done in core and the experience of converting an extension over. I imagine most people in the community are familiar with python 3 now, but there are some useful pointers like:
* setup travis to run the flake8 linting - the ckan extension templates have this now
* `from __future__ import unicode_literals`
* Declaring most strings as unicode `u'some string'` (am not entirely sure why we do, but we do)
* run the tests in python3 - will have to wait until CKAN core is done, I guess

**Comment by cclauss** [comment]
* [__six__ is part of the project requirements](https://github.com/ckan/ckan/blob/master/requirements.txt#L51)
* [Travis CI is running key flake8 tests on Python 3](https://github.com/ckan/ckan/blob/master/.travis.yml#L46)
* [Please read up on __unicode_literals__](http://python-future.org/imports.html#should-i-import-unicode-literals)

**Comment by davidread** [comment]
@cclauss I admit that it's not entirely clear, but @pwalsh and I are talking here specifically about a guide for migrating *CKAN Extensions*. So that's separate to the work you and others have done on ckan/ckan, which is all much appreciated by everyone. I'm simply suggesting we extend the same policies across to these repos as a starting point.

**Comment by pwalsh** [comment]
@davidread captured the migration guide in https://github.com/ckan/ckan/issues/4855

**Comment by mcarans** [comment]
Is the intention to release CKAN 2.9 with Python 3 support or will it be pushed back to a later version?

**Comment by cclauss** [comment]
105 days until Python 2 end of life.

**Comment by mcarans** [comment]
Thanks. Does everything in the tick list at the top of this issue (eg. vdm removal) need to be completed  for the 2.9 release?

**Comment by amercader** [comment]
@mcarans The plan is to support both Python 2 and 3 in CKAN 2.9, and make CKAN 3.0 Python 3 only

@cclauss thanks for the reminder! We are making slow but steady progress as reflected in the project board https://github.com/ckan/ckan/projects/3

We are focusing on various fronts, including the major blocker (VDM). Things will hopefully speed up as we approach the end of the year

**Comment by davidread** [comment]
Closing this issue in favour of this GitHub Project for keeping track of the remainder of this work:

*    GitHub Project: https://github.com/ckan/ckan/projects/3

See also:

*    Check the full roadmap here: https://hackmd.io/TI0UaFncR6yM9QIZDYxvsg
*    Python 3 issues: https://github.com/ckan/ckan/labels/Python%203
