### ISSUE TITLE
Patch Release July 2019

### ISSUE THREAD

**Issue by tino097** [ckan/ckan#4817]
Scheduled June 2019

### Starting up

- [x] Send email to CKAN announce / dev a week before
- [x] Update version on `dev-v2.8` branch to `2.8.3b`
- [x] Cherry-pick all issues marked as ["Backport 2.8.3 and "Backport Pending"](https://github.com/ckan/ckan/issues?utf8=%E2%9C%93&q=label%3A%22Backport+pending%22+label%3A%22Backport+2.8.3%22) to `dev-v2.8`

### Next few days

- [x] Pull translations on `dev-v2.8` branch
  - [x] `tx pull --all --minimum-perc=5 --force`
  - [x] Commit `*.po` files
  - [x] Compile `*.mo` files (`python setup.py compile_catalog`)
  - [x] Commit `*.mo` files
- [x] Build frontend (`paster front-end-build`), if there any changes commit them (there probably won't be)
- [x]  Update changelog in `dev-v2.8`
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine

### When the release is frozen

- [x] Update version on `dev-v2.8.3b` branch to `2.8.3`
- [x] Create tag `ckan-2.8.3`
- [x] Build final deb package

### Release day

- [x] Upload to https://packaging.ckan.org/
  - [x] Rename package to override existing 2.8 one
  - [x] Update md5sum
- [x] Upload to pypi (`pyhton setup.py sdist upload`)
- [ ]  Announce
  - [ ] ckan-announce and ckan-dev ([model](https://lists.okfn.org/pipermail/ckan-announce/2018-March/000035.html))
  - [ ] Twitter
  - [ ] ckan.org blog post (can be the same as the email announcement, changing the formatting)

### After release 

- [x] Cherry pick two i18n commit above to master
- [x] Update changelog in master with the 2.8.3 one
- [x] Merge `dev-2.8` into `2.8`
- [x] :beers: 

* same steps as above, for 2.7.6 and 2.6.8

**Comment by smotornyuk** [comment]
Update.
For all three branches([2.6](https://github.com/ckan/ckan/tree/dev-v2.6), [2.7](https://github.com/ckan/ckan/tree/dev-v2.7) and [2.8](https://github.com/ckan/ckan/tree/dev-v2.8)):
* PRs backported
* Changelog updated
* Front-end has been rebuilt
* Tested locally

**Comment by amercader** [comment]
Amazing @smotornyuk you are a star. I'll have some spare time at the end of the week, I'll see if we can wrap this up soon

**Comment by amercader** [comment]
Did a second and hopefully final round of backports, plus I'm in the process of fixing the Circle CI tests on 2.7 and 2.8

@smotornyuk can you update the changelog with the final changes? I don't think there is anything left to do apart from testing.

**Comment by smotornyuk** [comment]
Changelogs updated

**Comment by gallexme** [comment]
uhm? is it now released or not?
https://docs.ckan.org/en/ckan-2.8.3/ is missing

but https://pypi.org/project/ckan/ 
says 2.8.3

**Comment by amercader** [comment]
@gallexme yes, it is released. Unfortunately there are errors in the 2.8 Read the Docs build that make the old version show up: https://github.com/ckan/ckan/issues/4892

But the latest changelog include the released 2.8.3 changes: https://docs.ckan.org/en/latest/changelog.html#v-2-8-3-2019-07-03
