### ISSUE TITLE
CKAN 2.10 release

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7160]
Time has come to start the long overdue and highly anticipated CKAN 2.10 release :rocket: 

~~Optimistic target: before Christmas / More realistic target: Mid-January 2023 /~~ Even more realistic: Early-Mid February

# First steps

## Core

- [x] Create the `dev-v2.10` branch and change the version number on this branch to `2.10.0b`. From that moment on, everything that needs to go into the release needs to be merged first to master
- [x] Update version on `master` to `2.11.0a0` (we can always change it to `3.0.0a0`later)
- [x] Update beta.ckan.org to run using `dev-v2.10`, ideally updated daily
- [x] Extract translations and push a new `2.10` resource to Transifex. Full instructions on point 5 [here](https://docs.ckan.org/en/2.9/contributing/release-process.html#doing-the-beta-release)
- [x] Create `dev-v2.10` images (base + dev) and upload to: https://github.com/ckan/ckan-docker-base
- [x] Update the CKAN Dockerfiles to use `dev-v2.10` in the https://github.com/ckan/ckan-docker repo
- [x] Announce on the mailing list the start of the release process. From this moment on, anything that needs to go into 2.10 needs to be first merged to master and then cherry-picked to 2.10 (use the [Backport 2.10.0](https://github.com/ckan/ckan/labels/Backport%202.10.0) label + "Backport pending" to mark the relevant PRs)
- [x] Update packaging scripts to be able to build 2.10 (https://github.com/ckan/ckan-packaging/pull/21)
- [x] Finish pending issues / PRs (https://github.com/ckan/ckan/milestone/14), basically:
    - [x] Theme issues #6840 (more will probably come up during testing)
    - [x] Resource activities #6523: Only if the timing works and gets ready for review / reviewed / merged before the feature freeze
    - [x] ... (add if necessary)

## Extensions

- [x] Set up the `openknowledge/ckan-dev:2.10` Docker image to be automatically built from `dev-v2.10` (That's the image used by extensions to run the 2.10 tests, currently points to master)
- [x] Re-test extensions listed in #6787 as there have been major changes in core since we did the upgrades, mainly login refactor (which should only affect authorization related extensions) and CSRF protection. While CSRF protection will be optional on extensions in 2.10 it's very low-effort to add support for it by adding the necessary markup to extension forms (ckanext-scheming is done):
    ```
    <form ...>
        {{ h.csrf_input() if 'csrf_input' in h }}
    ```
# Following weeks: Stabilization

The following steps will likely be need to be repeated as we put more changes on the release branch. The idea is to keep it as usable and up to date as possible for testers:

- [x] Create the documentation branch from the release branch (`dev-v2.10`). This branch should be named `2.10` and should be kept up to date
- [x] Build CSS (`ckan sass`)
- [x] Update changelog in `dev-v2.10`. Run towncrier command plus manually add anything missing.
- [x] Test fixes for cherry-picked issues locally and on beta.ckan.org
- [x] Test that Debian package builds fine
- [x] Call for testing: blog post, mailing list and twitter
- [x] Call for translations

# Feature and translation freeze

A couple of weeks before the release date the release branch is frozen, no more merges except for fixes. We follow the standard [release process](http://docs.ckan.org/en/latest/contributing/release-process.html):

* [x] Pull translations
* [x] Rebuild CSS
* [x] Changelog

# Release day

* [x] Change version and tag 
* [x] Build and upload packages
* [x] Update docs (RTD)
* [x] PyPI
* [x] Announce
* [x] Post-release actions:
    * [x] Cherry-pick i18n changes from latest version to master
    * [x] Cherry-pick changelog entries for all new versions to master
    * [x] Update versions in `dev-v*` branches to the next version, including `b0`
    * [x] Update the Github labels to tag Backports to the next patch release number
- [ ] :beers: :tropical_drink:

**Comment by kowh-ai** [comment]
Maybe this would be a good time to include the new (official) CKAN config+setup (https://github.com/ckan/ckan-docker) and CKAN images (https://github.com/ckan/ckan-docker-base) repo’s as part of this release? Both repo's are close to finishing. I'd also rewrite the CKAN install with Docker documentation (https://docs.ckan.org/en/latest/maintaining/installing/install-from-docker-compose.html)

**Comment by pdelboca** [comment]
I have updated https://github.com/pdelboca/ckan-extensions-monitor to include all of the extensions listed in #6787 

I have also start checking on the test failing in `ckanext-sitesearch` since it is related to `The CSRF token is missing.` when executing forms in test context using `app.post(...)` method.

**Comment by amercader** [comment]
@kowh-ai yes! this is long overdue and feels like the perfect timing to remove the Docker setup included in this repo and point people to the better newer options. If you can focus on that that would be awesome. Make sure to update the release process docs to include whatever tasks we need to do maintain the Docker images (ie updating the images but maybe there's other stuff that needs to be done periodically or automated)

**Comment by amercader** [comment]
@ckan/core I've created the [`dev-v2.10`](https://github.com/ckan/ckan/tree/dev-v2.10) branch, so from now on everything that needs to be part of 2.10 needs to be marked with both the **Backport pending** and **Backport 2.10.0** labels (or even better submit 2 PRs, one for master and one for dev-v2.10)

**Comment by amercader** [comment]
CKAN 2.10.0 and 2.9.8 were released on 2023-02-15
